twitter_search/config/routes.rb
TwitterSearch::Application.routes.draw do
  root :to => 'welcome#home'
  get "twitter/search"
  post "twitter/search"
  resources :products do
	member do
		get 'nice_product_edit'
	end
	collection do
		get 'search'
		post 'launch_search'
	end
  end

  match ':controller(/:action(/:id))(.:format)'
end

twitter_search/app/controllers/twitter_controller.rb
class TwitterController < ApplicationController
require 'twitter_search'
def search
	if params[:twitter]
		@search_term = params[:twitter]
		client = TwitterSearch::Client.new('twitter_search')	# Initialize your Twitter client	
		@tweets = client.query(:q => "#{params[:twitter]}", :rpp => 25)# query the API for 25 results for the search term
	end
end
end

twitter_search/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

twitter_search/app/helpers/twitter_helper.rb
module TwitterHelper
end

twitter_search/app/helpers/welcome_helper.rb
module WelcomeHelper
end

twitter_search/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterSearch</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

twitter_search/app/views/twitter/_search.html.erb
<% unless @tweets.blank? %>
<div id="search_list">
	<table id = 'search_list_page' align = "center">
		<% @tweets.each do |i| %>
		<tr valign = "top" class= "<%= cycle('list-line-odd', 'list-line-even') %>">
			<td><%= link_to i.from_user, "http://twitter.com/#{i.from_user}", :class => "username", :target => "_blank" %></td>
			<td><%= i.text %></td>
			<td><%= time_ago_in_words i.created_at %></td>
		</tr>
		<%end%>
	</table>
</div>
<%end%>

twitter_search/app/views/twitter/search.html.erb
<%= javascript_include_tag :defaults %>

<script "/text/javascript">
	function submitIt(form){
		alert(there)
		if (form.twitter.value == ""){
			alert("Search is Empty")
			form.twitter.focus()
			return false
		}
		}
	
</script>



<h1> Twitter Search </h1>
<table align = "center">
<%= form_tag(:url => {:action => 'search'},:method => 'get', :id => "search",:onsubmit => 'return submitIt(this);' ) do %>
<tr>
	<td> <%= text_field_tag :twitter, @search_term, :size => 50 %> </td>
</tr>
<tr>
	<td align = "center"> <%= submit_tag 'search' %> </td>
</tr>
<% end %>
</table>
<br> </br>
<div id="search_list"><%= render 'search' %> </div>
<%unless @search_term.blank? %>
	<p align = "center"> <%= link_to "More tweets", :controller => 'twitter', :action => 'search', :twitter => @search_term %></p>
<%end%>

twitter_search/app/views/welcome/home.html.erb
<h1>Welcome</h1>


 <p align = "center">Click here to search the tweets in twitter <%= link_to 'Search', :controller => "twitter", :action => "search" %></p>
 <%= link_to "Products", new_product_path() %>